### ISSUE TITLE
Add images to your project card

### ISSUE THREAD

**Issue by Bavon101** [iLynette/my-portfolio#3]
- [x] I think your site would look much better if you added images for your projects

**Comment by Elerqsousy** [comment]
I believe in this part;

<section class="intro">
            <div class="content">
                <h1 class="about">Hey there. I’m <br>Lynette <br /><span>I’m a software<br/>developer</span></h1>
                <p class="introduction"> I can help you build a product , feature or website Look through some of my work and experience! If you like what you see and have a project you need coded, 
                don’t hesitate to contact me.
                </p>
                
                you can remove the <div> group and add the class="content" to the section. This way it's going to be more readable and also semantic.

in the second section;
  <section class="my-projects">
            <div class="down-arrow">
                <img src="./images/arrow.png" alt="down-arrow">
            </div>
I totally believe this image should be before the section and instead of containing in a div it can be directly posted inside the main and transfer the class to the img tag itself.

following in the same section here;
  <div class="title">
                <h2>My Recent Works</h2>
            </div>

            <div class="line">
                <img src="./images/greenline.png" alt="greenline">
            </div>

 <div class="project-container">
                    <div class="single-project">
                        <img src="./images/placeholder.png" alt="placeholder">
                        <div class="project-title">
                            <h4>Multi-Post Stories Gain+Glory</h4>
                        </div>
                        <ul class="tech-stack">
                            <li>Ruby on rails</li>
                            <li>css</li>
                            <li>JavaScript</li>
                            <li>html</li>
                        </ul>

div is not a semantic tag, so, I believe, you can remove them and add all content related to the card in hand inside an <article> and then add the h2 and img tags directly inside the article tag, so they get grouped together. and of course transfer the classes to them directly.
--------------------------------------

regarding CSS, I didn't get much look on the file, but I believe if you add margin-buttom of 5px or 10px to the buttons it will look magnificent!
